version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_stock_backtest

volumes:
  pgdata:
