services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
    command: bundle exec rails solid_queue:start
    volumes:
      - .:/app

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.docker

volumes:
  pgdata:
