class StockList
  GOOD_STOCKS = ["INDOFARM", "STALLION", "QPOWER"].freeze

  GMP_MINUS_40_30 = ["GLOTTIS", "OMFREIGHT"].freeze
  GMP_MINUS_30_20 = ["ARISINFRA", "BMWVENTLTD"].freeze
  GMP_MINUS_20_10 = ["LAXMIINDIA", "JARO"].freeze
  GMP_MINUS_10_0 = ["AJAXENGG", "ATHERENERG", "TRAVELFOOD", "INDIQUBE", "BRIGHOTEL", "MEIL", "VIKRAN", "VMSTMT", "IVALUE", "SAATVIKGL", "GANESHCP", "SOLARWORLD", "STYL", "EPACKPEB", "JKIPL", "PACEDIGITK", "FABTECH", "WEWORK"].freeze
  GMP_0_10 = ["AGARWALEYE", "HEXT", "BELRISE", "AEGISVOPAK", "SCODATUBES", "OSWALPUMPS", "KALPATARU", "IGCL", "SMARTWORKS", "MBEL", "JSWCEMENT", "ALLTIME", "BLUESTONE", "VIKRAMSOLR", "GEMAROMA", "SHREEJISPG", "AHCL", "DEVX", "EUROPRATIK", "GKENERGY", "ATLANTAELE", "ARSSBL", "TRUALT", "ADVANCE", "TATACAP", "CANHLIFE", "MIDWESTLTD"].freeze
  GMP_10_20 = ["DENTA", "BORANA", "HDBFS", "SAMBHV", "SHANTIGOLD", "PATELRMART", "AMANTA", "SHRINGARMS", "CRAMC"].freeze
  GMP_20_30 = ["LAXMIDENTL", "PROSTARM", "CRIZAC", "ANTHEM", "LOTUSDEV", "REGAAL", "RUBICON"].freeze
  GMP_30_40 = ["SGLTL", "ELLEN", "GLOBECIVIL", "JAINREC"].freeze
  GMP_40_50 = ["EBGNG", "LGEINDIA"].freeze
  GMP_50_60 = ["QUADFUTURE", "CPPLUS", "URBANCO"].freeze
  GMP_70_80 = ["HILINFRA"].freeze

  ETF_ABOVE_100 = ["SILVERBEES","GOLDBEES","NIFTYBEES"].freeze
  ETF_100_10 = (["LICMFGOLD","IVZINGOLD"] + ["HDFCSILVER", "SILVERIETF", "TATSILV", "SETFGOLD", "TATAGOLD", "HDFCGOLD", "GOLDIETF", "PSUBNKBEES", "MON100", "SBISILVER", "SILVERETF", "BANKBEES", "AXISGOLD", "SILVER", "MODEFENCE", "SETFNIF50", "JUNIORBEES", "GOLD1", "LOWVOLIETF", "SILVERCASE", "SILVER1", "AXISILVER", "GOLDETF", "PHARMABEES", "HDFCSML250", "MOGOLD", "NIFTYIETF", "MID150BEES", "GOLDSHARE"]).freeze
  ETF_10_1 = ["GOLDCASE", "HNGSNGBEES", "CPSEETF", "UTINIFTETF", "GROWWSLVR", "METALIETF", "SILVERADD", "ESILVER", "MAFANG", "SMALLCAP", "SILVERAG", "SETFNIFBK", "UTINEXT50", "GROWWGOLD", "MIDCAPETF", "NIFTYETF", "HEALTHY", "ICICIB22", "FMCGIETF", "MOSILVER", "GOLD360", "ALPHA", "LICMFGOLD", "AUTOBEES", "MOREALTY", "CONSUMIETF", "NEXT50IETF", "SETFNN50", "QGOLDHALF", "BANKETF", "BSLGOLDETF", "LIQGRWBEES", "MOCAPITAL", "UTISENSETF", "BANKIETF", "MOMENTUM50", "PVTBANIETF", "MIDCAPIETF", "HDFCNIFTY", "OILIETF", "TOP10ADD", "MOSMALL250", "MOM100", "AUTOIETF", "PSUBNKIETF", "UNIONGOLD", "MOM30IETF", "GROWWDEFNC", "GROWWRAIL", "FINIETF", "MONQ50", "MID150CASE", "GOLDETFADD", "SENSEXIETF", "MASPTOP50", "BBNPPGOLD", "MOVALUE", "CONSUMBEES", "METAL", "ABSLBANETF", "HDFCNIFBAN", "MONIFTY500", "HEALTHIETF"].freeze

  ETF_UNDER_20L = ["BANKBETF", "NV20BEES", "NIF100IETF", "LTGILTCASE", "LICNETFGSC", "EQUAL50ADD", "ECAPINSURE", "EVIETF", "SMALL250", "HDFCBSE500", "HDFCSENSEX", "MID150", "GROWWMOM50", "EMULTIMQ", "HDFCPVTBAN", "HDFCQUAL", "NIFTYQLITY", "GROWWSC250", "GROWWNIFTY", "AONENIFTY", "LICNMID100", "TECH", "MNC", "MSCIINDIA", "ABSLPSE", "GROWWN200", "VAL30IETF", "FLEXIADD", "ITETFADD", "HDFCNIF100", "NIFTY100EW", "HDFCLOWVOL", "UTISXN50", "PVTBANKADD"].freeze
  
  ETF_UNDER_20L_50L = ["EVINDIA", "DIVOPPBEES", "MOMOMENTUM", "MOMIDMTM", "NIFTY50ADD", "AONEGOLD", "SBIBPB", "BFSI", "NIFTYCASE", "CONSUMER", "AONETOTAL", "EGOLD", "BSE500IETF", "MOHEALTH", "HDFCNEXT50", "MAKEINDIA", "AXISVALUE", "MOMENTUM", "MULTICAP", "GROWWRLTY", "CHOICEGOLD", "NIF100BEES", "AXISNIFTY", "MIDSELIETF", "QUAL30IETF", "PSUBANKADD", "GROWWPOWER", "UTIBANKETF", "INTERNET", "SML100CASE", "TNIDETF", "GROWWNET", "HDFCPSUBK"].freeze
  
  ETF_UNDER_50L_1CR = ["ALPL30IETF", "GILT5YBEES", "ALPHAETF", "MIDSMALL", "IT", "INFRAIETF", "ITETF", "COMMOIETF", "HDFCNIFIT", "MIDCAP", "GROWWEV", "TOP100CASE", "PSUBANK", "BSLNIFTY", "SILVER360", "HDFCMOMENT", "SBIETFIT", "NV20IETF", "HDFCMID150", "BANKNIFTY1"].freeze

  MIX_1 = [ "MON100", "AXISGOLD", "BSLGOLDETF", "HDFCSML250", "ITBEES", "ITETF", "ITIETF", "SBIETFIT" ].freeze
  MIX_2 = [ "SBIETFIT" ].freeze
  MIX_3 = [ "FMCGIETF", "NIFTYBEES", "MON100", "ITETF", "ITIETF", "AXISGOLD", "BSLGOLDETF", "HDFCSML250", "HDFCBSE500" ].freeze

  # Multi Stock specific sets
  MS_SET_1 = ["MARUTI", "CDSL", "MAZDOCK", "BSE"].freeze
  MS_SET_2 = [ "BLUESTONE", "ALLTIME", "JSWCEMENT", "HILINFRA", "LOTUSDEV", "MBEL", "LAXMIINDIA", "CPPLUS", "SHANTIGOLD" ].freeze
  MS_SET_3 = [ "WIPRO", "RELIANCE", "IOC", "COALINDIA", "SBIN", "TMPV", "NTPC", "ADANIENT", "HCLTECH", "INFY", "ONGC", "ADANIPORTS", "TATACONSUM", "SUNPHARMA", "POWERGRID", "TITAN", "KOTAKBANK", "HDFCLIFE", "TECHM", "TCS", "JSWSTEEL", "ICICIBANK", "TATASTEEL", "HINDUNILVR", "BPCL", "HINDALCO", "UPL", "DRREDDY", "SBILIFE", "ASIANPAINT" ].freeze
  MS_SET_4 = [ "INDOFARM", "SGLTL", "QUADFUTURE", "LAXMIDENTL", "STALLION", "DENTA", "AGARWALEYE", "AJAXENGG", "HEXT", "QPOWER" ].freeze
  
  MS_ACTIVE = [ "FMCGIETF", "NIFTYBEES"].freeze
end
